### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by kwdunaway** [ekg/bamaddrg#5]
This repo does not have an explicit license in the base directory. Is this still covered under the MIT license like your other repos? If so, could you add the License to this repo?

**Comment by Damien-Black** [comment]
@ekg I noticed this issue was closed (by the submitter @kwdunaway ).

Just curious is there license information hidden somewhere? or a License we could add?

**Comment by ekg** [comment]
I should add MIT when I'm back at a computer.
